### PR TITLE
Abaccus python3 upgrade + minor changes

### PR DESCRIPTION
**Pull request by giacomomutti**
Dear all,

As requested by Prof. Gabaldon, I tried to update this script to make it python3/ETE3 compatible. First of all, thank you for providing me this insightful tool, I hope my other changes are in line with the work.

In order to test the changes I created two clean conda envs:

* one env had python2.7 and ete 2.3.10 with Abaccus1.0
* the other was with python3.6 and ete 3.1.2 with modified Abaccus

I checked and using the three examples the results were identical in both envs. I really hope I didn't miss any errors but maybe some further testing could be useful.

I did these minor changes:

* Whenever I could I removed for loops using list or set comprehension;
* I tweaked a bit the output. Notably, if no HGT is found the program now notices the user that the file is empty;
* Removed hard coding of ARATH in dinasty function;
* removed unused Abaccus function parameter: acceptor and donor, as they were not used;

Although I think I have a clear view of what the script does I have some doubts:

* why the thresholds were chosen this way? Meaning that, by design, L must be <= than J. So, there should not exist any case where J=2 and L=3. Therefore, based on my understanding, the defaults should be 3,3.
* Is the function euka_exlusive needed?

I had in mind to write a little script to define a function that takes as input ncbi taxon id and returns a taxonomy-like csv file, do you think that could be a good idea?

Finally, I propose to update software version to 1.1 and updated the README accordingly (I also updated it with ETE toolkit working link);

Regards and thanks again,\
Giacomo

### CODE REVIEW

**Comment by MANaranjo** [comment]
Hello,

Thank you very much for taking this task. Abaccus was a script that I wrote
long long ago, at the beginning of my PhD, and I understand there are many
things in there that are not as optimal as they should be.

With regards to the doubts.

   - You are right in the form that's implemented. However, this is only
   true because we are using an standarized topology. J (jump) is supposed to
   represent a filter for a minimum evolutionary distance (aka branch
   distance) between the organisms that harbor the sequences. Loses (L) is
   supposed to represent the number of inferred loses, which deppends on the
   topology, not the distance. J looks at the main taxonomic categories
   (species, genus, order, class, phylum) in order to avoid inflation when
   dealing with lineages that have very detailed taxonomies (i. e. they have
   tribes and subfamilies, and suborders and so on). Taking those intermediate
   taxonomic categories into consideration would "devaluate" J, but it would
   make L more informative.
   - euka_exclusive looks like a completely useless function. It was
   probably used at some point I don't remember, substitued by something else
   and left behind unchecked.

With regards of using taxids to generate a csv, yes, I think it's a great
idea. At some point I had plans on making it more flexible, but I couldn't
find time for that. Of course,  I would be more than willing to help you
improve Abaccus.

Let me know if you need anything,

Miguel

**Comment by giacomomutti** [comment]
Hello Miguel, nice to meet you! I'm Giacomo, a master student in bioinformatics in Milan. I will start my master thesis in a few weeks at Gabaldon's lab at BSC. Will I meet you there?

Thank you for replying so fast and adressing my doubts. I can only imagine what it must be like to revisit code written four years ago as sometimes I look at code I wrote few weeks earlier and I can't figure out what's going on.

Anyway, now I understand better the choices you made about J and L and they make completely sense. Also, given your approval, I'll work on the "taxonomier" function in the next days, even though, I imagine that there would be some issues as taxonomy itself is really flexible and hard to "automate".

Thanks again and have a nice weekend, 
Giacomo

**Comment by MANaranjo** [comment]
Hello and nice to meet you,

Unfortunately I left the lab in 2019. I like to visit them when I go to
Barcelona, but things are tricky now with covid. In any case, I'll be
available for anything you might need via mail or video call.

Enjoy your time at the lab. I'm sure they'll be sure you feel welcomed
there.

Best wishes,

Miguel

**Comment by Ethuer** [comment]
Hi Miquel.

How's life ? Hope you're doing great!
And how did I end up in this email chain, I thought I left the Gabaldon
github in 2017 and I have no connection to Abaccus whatsoever.

Enjoy the time in Barcelona, Giacomo and good luck with the old Gabaldon
codebases.

Best,
Ernst

**Comment by giacomomutti** [comment]
Hello and thanks for the wishes! I think that may be due to the fact you're "watching" the repository and thus you may receive pull requests notifications. You can modify this setting on the github page by clicking on the "watch" options.
Best regards, 
Giacomo

**Comment by MANaranjo** [comment]
Hi Ernst!

Nice to hear from you! Everything is fine over here. I hope the same for
you.
I think you appear in the list of "watchers" for this repository.
https://github.com/Gabaldonlab/Abaccus/watchers
Apologies for the inconveniences.

Best regards,

Miguel

**Pull request merged**
